// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for OrderStatus.
const (
	CANCELED       OrderStatus = "CANCELED"
	COMPLETED      OrderStatus = "COMPLETED"
	CREATED        OrderStatus = "CREATED"
	PAID           OrderStatus = "PAID"
	PAYMENTPENDING OrderStatus = "PAYMENT_PENDING"
	SHIPPED        OrderStatus = "SHIPPED"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case CANCELED:
		return true
	case COMPLETED:
		return true
	case CREATED:
		return true
	case PAID:
		return true
	case PAYMENTPENDING:
		return true
	case SHIPPED:
		return true
	default:
		return false
	}
}

// Defines values for ProductStatus.
const (
	ACTIVE   ProductStatus = "ACTIVE"
	ARCHIVED ProductStatus = "ARCHIVED"
	INACTIVE ProductStatus = "INACTIVE"
)

// Valid indicates whether the value is a known member of the ProductStatus enum.
func (e ProductStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case ARCHIVED:
		return true
	case INACTIVE:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	ADMIN  Role = "ADMIN"
	SELLER Role = "SELLER"
	USER   Role = "USER"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case ADMIN:
		return true
	case SELLER:
		return true
	case USER:
		return true
	default:
		return false
	}
}

// AccessTokenResponse defines model for AccessTokenResponse.
type AccessTokenResponse struct {
	AccessToken string `json:"access_token"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details   *map[string]interface{} `json:"details,omitempty"`
	ErrorCode string                  `json:"error_code"`
	Message   string                  `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// OrderCreate defines model for OrderCreate.
type OrderCreate struct {
	Items     []OrderItemRequest `json:"items"`
	PromoCode *string            `json:"promo_code,omitempty"`
}

// OrderItemRequest defines model for OrderItemRequest.
type OrderItemRequest struct {
	ProductId openapi_types.UUID `json:"product_id"`
	Quantity  int                `json:"quantity"`
}

// OrderItemResponse defines model for OrderItemResponse.
type OrderItemResponse struct {
	PriceAtOrder float32            `json:"price_at_order"`
	ProductId    openapi_types.UUID `json:"product_id"`
	Quantity     int                `json:"quantity"`
}

// OrderResponse defines model for OrderResponse.
type OrderResponse struct {
	CreatedAt      time.Time           `json:"created_at"`
	DiscountAmount float32             `json:"discount_amount"`
	Id             openapi_types.UUID  `json:"id"`
	Items          []OrderItemResponse `json:"items"`
	Status         OrderStatus         `json:"status"`
	TotalAmount    float32             `json:"total_amount"`
	UpdatedAt      time.Time           `json:"updated_at"`
	UserId         openapi_types.UUID  `json:"user_id"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderUpdate defines model for OrderUpdate.
type OrderUpdate struct {
	Items []OrderItemRequest `json:"items"`
}

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	Category    string        `json:"category"`
	Description *string       `json:"description,omitempty"`
	Name        string        `json:"name"`
	Price       float32       `json:"price"`
	Status      ProductStatus `json:"status"`
	Stock       int           `json:"stock"`
}

// ProductPage defines model for ProductPage.
type ProductPage struct {
	Content       []ProductResponse `json:"content"`
	Page          int               `json:"page"`
	Size          int               `json:"size"`
	TotalElements int               `json:"totalElements"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	Category    string             `json:"category"`
	CreatedAt   time.Time          `json:"created_at"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Price       float32            `json:"price"`
	Status      ProductStatus      `json:"status"`
	Stock       int                `json:"stock"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ProductStatus defines model for ProductStatus.
type ProductStatus string

// ProductUpdate defines model for ProductUpdate.
type ProductUpdate = ProductCreate

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     Role                `json:"role"`
}

// Role defines model for Role.
type Role string

// TokensResponse defines model for TokensResponse.
type TokensResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// AccessDenied defines model for AccessDenied.
type AccessDenied = ErrorResponse

// ProductNotFound defines model for ProductNotFound.
type ProductNotFound = ErrorResponse

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Page     *int           `form:"page,omitempty" json:"page,omitempty"`
	Size     *int           `form:"size,omitempty" json:"size,omitempty"`
	Status   *ProductStatus `form:"status,omitempty" json:"status,omitempty"`
	Category *string        `form:"category,omitempty" json:"category,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = RefreshRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody = OrderCreate

// PutOrdersIdJSONRequestBody defines body for PutOrdersId for application/json ContentType.
type PutOrdersIdJSONRequestBody = OrderUpdate

// PostProductsJSONRequestBody defines body for PostProducts for application/json ContentType.
type PostProductsJSONRequestBody = ProductCreate

// PutProductsIdJSONRequestBody defines body for PutProductsId for application/json ContentType.
type PutProductsIdJSONRequestBody = ProductUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Refresh access token
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// Register user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Create order (USER, ADMIN)
	// (POST /orders)
	PostOrders(w http.ResponseWriter, r *http.Request)
	// Get order
	// (GET /orders/{id})
	GetOrdersId(w http.ResponseWriter, r *http.Request, id OrderId)
	// Update order
	// (PUT /orders/{id})
	PutOrdersId(w http.ResponseWriter, r *http.Request, id OrderId)
	// Cancel order
	// (POST /orders/{id}/cancel)
	PostOrdersIdCancel(w http.ResponseWriter, r *http.Request, id OrderId)
	// List products
	// (GET /products)
	GetProducts(w http.ResponseWriter, r *http.Request, params GetProductsParams)
	// Create product (SELLER, ADMIN)
	// (POST /products)
	PostProducts(w http.ResponseWriter, r *http.Request)
	// Soft delete product (ARCHIVED)
	// (DELETE /products/{id})
	DeleteProductsId(w http.ResponseWriter, r *http.Request, id ProductId)
	// Get product by ID
	// (GET /products/{id})
	GetProductsId(w http.ResponseWriter, r *http.Request, id ProductId)
	// Update product (SELLER own, ADMIN)
	// (PUT /products/{id})
	PutProductsId(w http.ResponseWriter, r *http.Request, id ProductId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh access token
// (POST /auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create order (USER, ADMIN)
// (POST /orders)
func (_ Unimplemented) PostOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get order
// (GET /orders/{id})
func (_ Unimplemented) GetOrdersId(w http.ResponseWriter, r *http.Request, id OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update order
// (PUT /orders/{id})
func (_ Unimplemented) PutOrdersId(w http.ResponseWriter, r *http.Request, id OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel order
// (POST /orders/{id}/cancel)
func (_ Unimplemented) PostOrdersIdCancel(w http.ResponseWriter, r *http.Request, id OrderId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List products
// (GET /products)
func (_ Unimplemented) GetProducts(w http.ResponseWriter, r *http.Request, params GetProductsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create product (SELLER, ADMIN)
// (POST /products)
func (_ Unimplemented) PostProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft delete product (ARCHIVED)
// (DELETE /products/{id})
func (_ Unimplemented) DeleteProductsId(w http.ResponseWriter, r *http.Request, id ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get product by ID
// (GET /products/{id})
func (_ Unimplemented) GetProductsId(w http.ResponseWriter, r *http.Request, id ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update product (SELLER own, ADMIN)
// (PUT /products/{id})
func (_ Unimplemented) PutProductsId(w http.ResponseWriter, r *http.Request, id ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersId operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutOrdersId operation middleware
func (siw *ServerInterfaceWrapper) PutOrdersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutOrdersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersIdCancel operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersIdCancel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id OrderId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersIdCancel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProducts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostProducts operation middleware
func (siw *ServerInterfaceWrapper) PostProducts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProductsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProductsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProductsId operation middleware
func (siw *ServerInterfaceWrapper) GetProductsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProductsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutProductsId operation middleware
func (siw *ServerInterfaceWrapper) PutProductsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutProductsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.PostOrders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{id}", wrapper.GetOrdersId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/orders/{id}", wrapper.PutOrdersId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders/{id}/cancel", wrapper.PostOrdersIdCancel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products", wrapper.GetProducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/products", wrapper.PostProducts)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/products/{id}", wrapper.DeleteProductsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products/{id}", wrapper.GetProductsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/products/{id}", wrapper.PutProductsId)
	})

	return r
}
